WITH CREDIT_CARD AS 
(

SELECT
    TRIM(CREDITCARDID) :: INT  as CREDIT_CARD_ID,
    TRIM(LOWER(CARDTYPE)) as CARD_TYPE,
    TRIM(CARDNUMBER) as CARD_NUMBER,
    YEAR(EXPYEAR) as EXP_YEAR,
    MONTH(EXPMONTH) as EXP_MONTH,
    MODIFIEDDATE as MODIFIED_DATE
FROM {{ ref ('creditcard')}}
)

SELECT * FROM CREDIT_CARD
