WITH ADDRESS AS (

SELECT 
    TRIM(LOWER(ADDRESSID )) AS ADDRESS_ID,
    TRY_CAST(STATEPROVINCEID AS INT) AS STATE_PROVINCE_ID,
    TRIM(LOWER(ADDRESSLINE1)) AS ADDRESS_LINE_1,
    TRIM(LOWER(ADDRESSLINE2)) AS ADDRESS_LINE_2,
    TRIM(LOWER(CITY)) AS CITY,
    TRIM(LOWER(POSTALCODE)) AS POSTAL_CODE,
    TRIM(LOWER(SPATIALLOCATION)) AS SPATIAL_LOCATION,
    TRIM(LOWER(ROWGUID)) AS ROW_GUID,
    TRIM(LOWER(MODIFIEDDATE)) AS MODIFIED_DATE
FROM {{ ref('address') }}
)

SELECT * FROM ADDRESS

