WITH PRODUCT AS
(

SELECT
    PRODUCTID as PRODUCT_ID,
    PRODUCTMODELID as PRODUCT_MODEL_ID,
    PRODUCTSUBCATEGORYID as PRODUCT_SUB_CATEGORY_ID,
    NAME as PRODUCT_NAME,
    SAFETYSTOCKLEVEL as SAFETY_STOCK_LEVEL,
    FINISHEDGOODSFLAG as FINISHED_GOODS_FLAG,
    CLASS as CLASS,
    MAKEFLAG as MAKE_FLAG,
    PRODUCTNUMBER as PRODUCT_NUMBER,
    REORDERPOINT as REORDER_POINT, 
    ROWGUID as ROW_GUID,
    WEIGHTUNITMEASURECODE as WEIGHT_UNIT_MEASURE_CODE,
    STANDARDCOST as STANDARD_COST,
    LISTPRICE as LIST_PRICE,
    PRODUCTLINE as PRODUCT_LINE,
    COLOR as COLOR,
    WEIGHT as WEIGHT,
    DAYSTOMANUFACTURE as DAYS_TO_MANUFACTURE,
    MODIFIEDDATE as MODIFIED_DATE,
    SELLSTARTDATE as SELL_START_DATE
FROM {{ ref ('product')}}
)

SELECT * FROM PRODUCT