WITH PRODUCT_CATEGORY AS
(
SELECT 
    PRODUCTCATEGORYID AS PRODUCT_CATEGORY_ID,
    NAME AS PRODUCT_NAME,
    MODIFIEDDATE AS MODIFIED_DATE
FROM {{ ref('productcategory')}}
)

SELECT * FROM PRODUCT_CATEGORY