WITH ADDRESS AS (

SELECT 
    ADDRESSID AS ADDRESS_ID,
    STATEPROVINCEID AS STATE_PROVINCE_ID,
    ADDRESSLINE1 AS ADDRESS_LINE_1,
    ADDRESSLINE2 AS ADDRESS_LINE_2,
    CITY AS CITY,
    POSTALCODE AS POSTAL_CODE,
    SPATIALLOCATION AS SPATIAL_LOCATION,
    ROWGUID AS ROW_GUID,
    MODIFIEDDATE AS MODIFIED_DATE
FROM {{ ref('address') }}
)

SELECT * FROM ADDRESS

