WITH PRODUCT_SUBCATEGORY AS
(
SELECT 
    PRODUCTSUBCATEGORYID AS PRODUCT_SUBCATEGORY_ID,
    PRODUCTCATEGORYID AS PRODUCT_CATEGORY_ID,
    NAME AS PRODUCT_NAME,
    MODIFIEDDATE AS MODIFIED_DATE
FROM {{ ref('productsubcategory')}}
)

SELECT * FROM PRODUCT_SUBCATEGORY